### ISSUE TITLE
Encounter overflow when running test.py

### ISSUE THREAD

**Issue by rundiwu** [nschor/CompoNet#1]
Hi, after I successfully trained the model as suggested in the README, I encounter overflow when running `test.py` by `python test.py --model_path log/best_model_epoch_174.ckpt`:
```
show3d_balls.py:35: RuntimeWarning: overflow encountered in square
  radius = ((xyz ** 2).sum(axis=-1) ** 0.5).max()
```
Then the visualization becomes a white point in the middle, which is definitely caused by the overflow problem. So i checked the raw output of the network in `test.py` (`preds` in function `generate_shapse_from_vectors`), and it turns out its values are of `1e21` magnitude... Is it reasonable? Or did I miss something?

Thanks if you can help.

**Comment by nschor** [comment]
Hi Chris Wu,
Thank you for your interest in our work.
The values of `preds` suppose to be around 0.0x-0.x.
When training, did you use only `python train.py` or did you use other flags?
Here is an example of trained model, on the chair category:
[model_example.zip](https://github.com/nschor/CompoNet/files/3757522/model_example.zip)
Please check that you can load the model and generate new chairs using it.
Best,
Nadav

**Comment by rundiwu** [comment]
Thanks for reply!
I tried your trained model by running `python test.py --model_path log/model_example/model.ckpt` and still met the same problem. I add a line in `test.py` to see value range of `preds`:
```python
       preds = np.concatenate((pred[0, 0], pred[0, 1]), axis=0)
        for p in xrange(2, NUM_PARTS):
            preds = np.concatenate((preds, pred[0, p]), axis=0)

        print(np.max(preds), np.min(preds))   # I add this line
```
The stdout is:
```
Embedding part 0
Compute GMM for part 0
/home/megaBeast/anaconda3/envs/CompoNet/lib/python2.7/site-packages/sklearn/mixture/base.py:237: ConvergenceWarning: Initialization 1 did not converge. Try different init parameters, or increase max_iter, tol or check for degenerate data.
  % (init + 1), ConvergenceWarning)
/home/megaBeast/anaconda3/envs/CompoNet/lib/python2.7/site-packages/sklearn/mixture/base.py:394: RuntimeWarning: covariance is not symmetric positive-semidefinite.
  self.means_, self.covariances_, n_samples_comp)])
Embedding part 1
Compute GMM for part 1
Embedding part 2
Compute GMM for part 2
Embedding part 3
Compute GMM for part 3
(3.6866776e+30, -4.3219307e+30)
```
The `preds` is still of `1e30` magnitude. You can see there is a warning from `sklearn/mixture/base.py`, is this where the problem comes from?

**Comment by nschor** [comment]
I see that you use the environment I uploaded, which uses python 2.7, but you use it with Anaconda 3. Maybe this is the source for you issue?
