### ISSUE TITLE
reuslts of data

### ISSUE THREAD

**Issue by CRISZJ** [nschor/CompoNet#2]
hi , could you please offer some results of this Network? thanks :-)

**Comment by nschor** [comment]
Hi :)
I uploaded a trained model - see https://github.com/nschor/CompoNet/issues/1
You can use it to generate some results in the Chair category.

**Comment by CRISZJ** [comment]
thanks, I've solved it

**Comment by duzhenjiang113** [comment]
I meet some error when i train the airplane.  The results generated by test are confusing,  can you provide more pre-trained models？ Thanks
